/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'timbo' at '02/02/15 15:35' with Gradle 2.2.1
 *
 * @author timbo, @date 02/02/15 15:35
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
